name: OnMergeRelease

on:
  push:
    branches:
      - 'main'
      - 'release/*'
    tags:
      - '**'

permissions: read-all

jobs:
  build-test:
    runs-on: [ ubuntu-20.04 ]
    env:
      http_proxy: ${{ secrets.HTTP_PROXY }}
      https_proxy: ${{ secrets.HTTPS_PROXY }}
      no_proxy: ${{ secrets.NO_PROXY }}
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0
        with:
          fetch-depth: 0

      - name: Build libraries and examples
        run: make all

      - name: Unit Test Coverage
        run: |
          test_output=$(make test-coverage)
          if [ $? -ne 0 ]; then
            echo "Unit tests failed"
            exit 1
          fi
          COVERAGE=$(make test-coverage | grep 'Total:|' | awk -F\| '{print $2}' | awk -F. '{print $1}')
          echo "Unit test coverage for Client is - $COVERAGE%"
          if [[ $COVERAGE -lt 70 ]]; then
            echo "Unit test coverage must be above 70%"
            exit 1
          fi
